productly/productly/urls.py
#
# Course: ultimate python
# https://www.udemy.com/course/ultimate-python-de-cero-a-programador-experto/
#

"""productly URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.inicio,name="inicio"),
    path("admin/", admin.site.urls),
    path('productos/',include('productos.urls')),
]

productly/productos/urls.py
#
# Course: ultimate python
# https://www.udemy.com/course/ultimate-python-de-cero-a-programador-experto/
#
#
from django.urls import path
from  . import views
app_name = 'productos'
urlpatterns=[
    path('',views.index,name = 'index'),
    path('formulario',views.formulario,name='formulario'),
    path('<int:producto_id>',views.detalle,name = 'detalle'),
]

productly/productos/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=255)
    def __str__(self):
        return self.nombre
        

class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    stock = models.IntegerField()
    puntaje = models.FloatField()
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    creado_en=models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.nombre
        

                  

productly/productos/forms.py
from . import models
from django.forms import ModelForm

class ProductoForm (ModelForm):
    class Meta:
        model = models.Producto
        fields=['nombre','stock','puntaje','categoria']

productly/productly/views.py
from django.shortcuts import render

def inicio(request):
    return render(
        request,
        'inicio.html',
    )

productly/productos/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render,get_object_or_404
from .models import Producto
from .forms import  ProductoForm
# Create your views here.

def index(request):
    productos = Producto.objects.all()
    # productos = Producto.objects.filter(puntaje = 3)
    # productos = Producto.objects.get(pk=1)
    return render (
        request,
        'index.html',
        context={'productos': productos}
    )

# def detalle (request,producto_id):
#     try:
#         producto = Producto.objects.get(id = producto_id)
#         return render (request,'detalle.html',context={'producto':producto})
#     except Producto.DoesNotExist:
#         raise Http404()


def detalle (request,producto_id):
    producto = get_object_or_404(Producto,id=producto_id)
    return render (request,'detalle.html',context={'producto':producto})

def formulario(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productos')
    else:
        form = ProductoForm()
        
    return render(
        request,
        'producto_form.html',
        {'form':form}
    )

productly/productos/templates/detalle.html
{% extends 'base.html' %}

{% block content %}

<div>
    <h6>{{ producto.nombre }}</h6>
    <p>{{ producto.categoria }}</p>
    <p>{{ producto.stock }}</p>
    <p>{{ producto.puntaje }}</p>
    <p>{{ producto.creado_en }}</p>
</div>


{% endblock %}

productly/productos/templates/form_snippet.html
{% load add_attr %}
{% for field in form %}
<div class="mb-3">
    {{ field.label_tag }}
    {% if field.errors %}
        {{ field|add_attr:"class:is-invalid" }}
    {% else %}
        {{ field }}
    {% endif %}
    <div class="invalid_feedback">
        {% for error in field.errors %}
            {{ error }}
        {% endfor %}
    </div>
</div>
{% endfor %}

productly/productos/templates/index.html
{% extends 'base.html' %}

{% block content %}
    
<h1>Productos</h1>
<a href="{% url 'productos:formulario' %}">Nuevo productos</a>
<table class="table">
    <thead>
        <tr>
            <th>nombre</th>
            <th>stock</th>
            <th>Puntaje</th>
            <th>categoria</th>
        </tr>
    </thead>
    <tbody>
        {% for producto in productos %}
        <tr>
            <td>
                <a href = "{% url 'productos:detalle' producto.id %}">
                {{ producto.nombre }}
                </a>
            </td>
            <td>{{ producto.stock }}</td>
            <td>{{ producto.puntaje }}</td>
            <td>{{ producto.categoria }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

productly/productos/templates/producto_form.html
{% extends 'base.html' %}

{% block content %}

<form novalidate action="{% url 'productos:formulario' %}" method='post'>
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Enviar" />
</form>

{% endblock %}

productly/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'productos:index' %}">Productos</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

productly/templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %} class="form-label">{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

productly/templates/django/forms/widgets/input.html
<input 
class="form-control {{ widget.attrs.class }}"
type="{{ widget.type }}" 
name="{{ widget.name }}"
{% if widget.value != None %} 
    value="{{ widget.value|stringformat:'s' }}"
{% endif %}
{% include "django/forms/widgets/attrs.html" %}
>

productly/templates/django/forms/widgets/select.html
<select class="form-select" name="{{ widget.name }}
    {% include "django/forms/widgets/attrs.html" %}>
    {% for group_name, group_choices, group_index in widget.optgroups %}
        {% if group_name %}
            <optgroup label="{{ group_name }}">
        {% endif %}
        {% for option in group_choices %}
            {% include option.template_name with widget=option %}
        {% endfor %}
        {% if group_name %}
            </optgroup>
        {% endif %}
    {% endfor %}
</select>

productly/templates/inicio.html
{% extends "base.html" %}

{% block content %}
    Hola este  es productly
{% endblock content %}